### ISSUE TITLE
1. Sorting by number of consonants

### ISSUE THREAD

**Issue by IEH-tekmexico** [shardool/exercises_ch1_ch6#1]
It would be best to not create the same regular expression over-and-over. Save the regex in a variable and use a closure to avoid creating it multiple times and on every function execution.

**Comment by shardool** [comment]
made the suggested change. Request you to review and close

**Comment by shardool** [comment]
used closure to share the same RegExp object across multiple functions

**Comment by IEH-tekmexico** [comment]
Though the code changes do prevent the regular expression from being compiled on each execution, it is now accessible on the global scope. The use of the closure should also encapsulate it to only be available from the sorting function.

**Comment by shardool** [comment]
the closure is now scoped to the function that needs it and not in the global scope. Thanks for pointing this out to me.

**Comment by shardool** [comment]
Please close the issue if it looks alright now :)
