### ISSUE TITLE
5. Function that counts the number of vowels or digits

### ISSUE THREAD

**Issue by IEH-tekmexico** [shardool/exercises_ch1_ch6#4]
* A string formatted as a number is still a string. Use *instanceof Number* instead
* There is no need to create the same regular expression over-and-over

**Comment by shardool** [comment]
Made the suggested change. Request you to review and close.

**Comment by IEH-tekmexico** [comment]
The issue described in the second bullet point is still outstanding.

**Comment by shardool** [comment]
Close this issue if I got the "Closure" right :) Thanks again

**Comment by IEH-tekmexico** [comment]
refactor line 188:
```javascript
 return input.match(pat) ? input.match(new RegExp(pat)).length : 0;
```

**Comment by shardool** [comment]
done. Please review and close

**Comment by IEH-tekmexico** [comment]
Still needs refactoring off line 192
```javascript
return input.match(pat) ? input.match(pat).length : 0;
```
Don't repeat yourself.
